services:
  - type: web
    name: ai-fashion-backend
    runtime: docker
    image:
      url: docker.io/newbie028/ai-fashion-backend:latest
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 8000
      - key: DATABASE_URL
        fromDatabase:
          name: fashion-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: fashion-redis
          property: connectionString
    healthCheckPath: /health

  - type: redis
    name: fashion-redis
    plan: starter

databases:
  - name: fashion-db
    databaseName: fashion_jvy9
    user: fashion_jvy9_user
