# Render.yaml removed - manual setup required
# Go to render.com dashboard and:
# 1. Delete existing service
# 2. Create new Web Service  
# 3. Select Python 3.13 environment
# 4. Set build command: pip install -r backend/requirements.txt
# 5. Set start command: uvicorn main:app --host 0.0.0.0 --port $PORT
